name: Cryptocurrency

dependencies:
  - base
  - containers
  - unordered-containers
  - bytestring
  - binary
  - mtl
  - aeson
  - time
  - crypto-api
  - cryptohash-sha256
  - RSA
  - network
  - network-transport
  - async
  - utf8-string
  - stm
  - DRBG

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - Cryptocurrency
      - QuickCheck
      - parallel
      - combinat
      - quickcheck-instances
