name: Cryptocurrency

# ghc-options: -Wall

dependencies:
  - base
  - containers
  - unordered-containers
  - bytestring
  - binary
  - mtl
  - aeson
  - time
  - crypto-api
  - cryptohash-sha256
  - RSA
  - network
  - async
  - utf8-string
  - stm
  - stm-chans
  - DRBG
  - optparse-applicative
  - bytestring-conversion
  - sampling
  - deepseq
  - hasql
  - hasql-transaction
  - hasql-pool
  - vector
  - text
  - contravariant-extras
  - universe-base
  - stm-io-hooks
  - base64-bytestring
  - yaml

library:
  source-dirs: src

executables:

  wallet:
    main: wallet.hs
    source-dirs: app
    dependencies:
      - Cryptocurrency

  miner:
    main: miner.hs
    source-dirs: app
    dependencies:
      - Cryptocurrency

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - Cryptocurrency
      - QuickCheck
      - parallel
      - combinat
      - quickcheck-instances
      - pretty-simple
