
CREATE TYPE transactionStatus AS ENUM ('validated', 'waiting', 'discarded');

-- transaction is NOT a reserved keyword in postgreSQL, it is in standard SQL
create table transaction (
    txId bytea primary key,
    txBlockId bytea not null,
    txData jsonb not null,
    txStatus transactionStatus not null
    -- check ( txStatus != 'validated' or (txblockid is not null) )
)

create table fixedHeader (
    blockid bytea primary key,
    headerData jsonb not null
)