walletDatabaseConfig: null
targetDifficulty: 11
forkMaxDiff: 10
peersFilepath: app/data/peers_miner2.json
loggingMode:
  contents: miner-logs2
  tag: ToFile
port: '49002'
blockchainFilepath: app/data/fixed_blocks2.json
blockchainGenesis: Złoty
minerWaitForTxs: false
