databaseConfig:
  connectionSettings:
    dbhost: localhost
    dbport: 5432
    dbuser: postgres
    database: 'wallet_db'
    dbpassword: ''
  timeout: 30
  poolSize: 4
nodeConfig:
  peersFilepath: app/data/peers_wallet.json
  loggingMode:
    tag: ToStdout
  port: '49003'
blockchainConfig:
  targetDifficulty: 12
  forkMaxDiff: 10
  blockchainGenesis: Złoty
replPort: '49050'
